//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHTH_65133373.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaHD { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal PhanTramGiam { get; set; }
        public decimal TienGiam { get; set; }
        public decimal ThanhTien { get; set; }
        public Nullable<int> MaKM { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual ChiTietKhuyenMai ChiTietKhuyenMai { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
