create database QLHH;
go
use QLHH;
go

create table KHACHHANG 
(
	MAKHACHHANG VARCHAR(10) NOT NULL PRIMARY KEY,
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL
);

CREATE TABLE NHANVIEN
(
	MANHANVIEN VARCHAR(10) NOT NULL PRIMARY KEY,
	HO NVARCHAR(30) NOT NULL,
	TEN NVARCHAR(10) NOT NULL,
	NGAYSINH DATE NOT NULL,
	NGAYLAMVIEC DATE NOT NULL, 
	DIACHI NVARCHAR(100) NOT NULL, 
	DIENTHOAI VARCHAR(20) NULL,
	LUONGCOBAN MONEY NOT NULL,
	PHUCAP MONEY NOT NULL
);

CREATE TABLE NHACUNGCAP
(
	MACONGTY VARCHAR(10) NOT NULL PRIMARY KEY,
	TENCONGTY NVARCHAR(100) NOT NULL,
	TENGIAODICH NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	DIENTHOAI VARCHAR(20) NOT NULL,
	FAX VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(20) NOT NULL
);

CREATE TABLE LOAIHANG
(
	MALOAIHANG VARCHAR(10) NOT NULL PRIMARY KEY,
	TENLOAIHANG NVARCHAR(100) NOT NULL
);

CREATE TABLE MATHANG
(
	MAHANG VARCHAR(10) NOT NULL PRIMARY KEY,
	TENHANG NVARCHAR(100) NOT NULL,
	MACONGTY VARCHAR(10) NOT NULL,
	MALOAIHANG VARCHAR(10) NOT NULL,
	SOLUONG DECIMAL(10,2) NOT NULL,
	DONGVITINH NVARCHAR(20) NOT NULL,
	GIAHANG MONEY NOT NULL
	CONSTRAINT FK_MATHANG_NHACUNGCAP
	FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
	CONSTRAINT FK_MATHANG_LOAIHANG
	FOREIGN KEY (MALOAIHANG) REFERENCES LOAIHANG(MALOAIHANG)
);

CREATE TABLE DONDATHANG
(
	SOHOADON VARCHAR(10) NOT NULL PRIMARY KEY,
	MAKHACHHANG VARCHAR(10) NOT NULL,
	MANHANVIEN VARCHAR(10) NOT NULL,
	NGAYDATHANG DATETIME NULL,
	NGAYGIAOHANG DATETIME NULL, 
	NGAYCHUYENHANG DATETIME NULL,
	NOIGIAOHANG NVARCHAR(100) NULL,
	CONSTRAINT FK_DONDATHANG_KHACHHANG
	FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
	CONSTRAINT FK_DONDATHANG_NHANVIEN
	FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
);

CREATE TABLE CTDONHANG
(
	SOHOADON VARCHAR(10) NOT NULL,
	MAHANG VARCHAR(10) NOT NULL,
	PRIMARY KEY(SOHOADON, MAHANG),
	GIABAN MONEY NOT NULL,
	SOLUONG DECIMAL(10,2) NOT NULL, 
	MUCGIAMGIA DECIMAL(4,2) NOT NULL
	CONSTRAINT FK_CTDONHANG_DONDATHANG
	FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
	CONSTRAINT FK_CTDONHANG_MATHANG
	FOREIGN KEY (MAHANG) REFERENCES MATHANG(MAHANG)
);
